change LF for stats

diff --git a/azure.yaml b/azure.yaml
--- a/azure.yaml
+++ b/azure.yaml
@@ -1,22 +1,21 @@
 # yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
-
-name: tdd-azd-nestedhv-dc-rtr
+name: tdd-infra-dev-containers
 metadata:
-    template: tdd-azd-nestedhv-dc-rtr@1.0.0
+  template: tdd-infra-dev-containers@0.0.1-beta
 infra:
    provider: "bicep"
 
 hooks:
-postprovision:
-    windows: # Run referenced script that uses environment variables (script shown below)
+  postprovision:
+    windows:
       shell: pwsh
       run: ./scripts/postprovision.ps1
       interactive: true
       continueOnError: false
     posix:
       shell: sh
-      run: chmod +x ./scripts/postprovision.sh
-      shell: sh
-      run: ./scripts/postprovision.sh
+      run: |
+        chmod +x ./scripts/postprovision.sh || echo "chmod failed, running anyway..."
+        ./scripts/postprovision.sh
       interactive: true
       continueOnError: false
